name: Slack Notifications

on:
  push:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - run: echo "💡 The ${{ github.repository }} repository, PR ${{ github.actor }} Base ref ${{ github.base_ref	}} event ${{ github.event	}}  has been cloned to the runner."
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C032C8WFAES\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Commit Pushed:* ${{ github.event.head_commit.message }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.actor }}\n*Repo:* ${{ github.repository }}\"}}\"}}]}' 



