name: Slack Notifications

on:
  push:
    branches: [ master ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@master
      with:
        args: '{\"channel\":\"C032C8WFAES\",\"text\":\"Hello world ${{ github.repository }} \"}'


